/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author larisasabalin
 */
public class AddIncome extends javax.swing.JDialog {

    /**
     * Creates new form AddIncome
     */
    public AddIncome(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        frmIncome_lblStatus1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        frmIncome_mnuOperations1 = new javax.swing.JMenu();
        frmIncome_miAddIncome1 = new javax.swing.JMenuItem();
        frmIncome_miAddExpenses1 = new javax.swing.JMenuItem();
        frmIncome_miGoToReports1 = new javax.swing.JMenuItem();
        frmIncome_miSeeBudgets1 = new javax.swing.JMenuItem();
        frmIncome_miSeeExpenses1 = new javax.swing.JMenuItem();
        frmIncome_miSeeIncome1 = new javax.swing.JMenuItem();
        frmIncome_mnuExport1 = new javax.swing.JMenu();
        frmIncome_miCSV1 = new javax.swing.JMenuItem();
        frmIncome_miPDF1 = new javax.swing.JMenuItem();
        frmIncome_mnuExit1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registering income", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans Typewriter", 1, 12))); // NOI18N

        jLabel28.setText("Name");

        jLabel29.setText("...");

        jLabel30.setText("Amount");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton4.setText("Save");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel29)
                                .addGap(0, 157, Short.MAX_VALUE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        frmIncome_lblStatus1.setText("Status");
        getContentPane().add(frmIncome_lblStatus1, java.awt.BorderLayout.PAGE_END);

        frmIncome_mnuOperations1.setText("Operations");
        frmIncome_mnuOperations1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 14)); // NOI18N

        frmIncome_miAddIncome1.setText("Add Income");
        frmIncome_mnuOperations1.add(frmIncome_miAddIncome1);

        frmIncome_miAddExpenses1.setText("Add Expenses");
        frmIncome_mnuOperations1.add(frmIncome_miAddExpenses1);

        frmIncome_miGoToReports1.setText("Go To Reports");
        frmIncome_mnuOperations1.add(frmIncome_miGoToReports1);

        frmIncome_miSeeBudgets1.setText("See Budget");
        frmIncome_miSeeBudgets1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmIncome_miSeeBudgets1ActionPerformed(evt);
            }
        });
        frmIncome_mnuOperations1.add(frmIncome_miSeeBudgets1);

        frmIncome_miSeeExpenses1.setText("See Expenses");
        frmIncome_mnuOperations1.add(frmIncome_miSeeExpenses1);

        frmIncome_miSeeIncome1.setText("See Income");
        frmIncome_mnuOperations1.add(frmIncome_miSeeIncome1);

        jMenuBar2.add(frmIncome_mnuOperations1);

        frmIncome_mnuExport1.setText("Export");
        frmIncome_mnuExport1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 14)); // NOI18N

        frmIncome_miCSV1.setText("to CSV");
        frmIncome_mnuExport1.add(frmIncome_miCSV1);

        frmIncome_miPDF1.setText("to PDF");
        frmIncome_mnuExport1.add(frmIncome_miPDF1);

        jMenuBar2.add(frmIncome_mnuExport1);

        frmIncome_mnuExit1.setText("Exit");
        frmIncome_mnuExit1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 14)); // NOI18N
        jMenuBar2.add(frmIncome_mnuExit1);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void frmIncome_miSeeBudgets1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmIncome_miSeeBudgets1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frmIncome_miSeeBudgets1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddIncome dialog = new AddIncome(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel frmIncome_lblStatus1;
    private javax.swing.JMenuItem frmIncome_miAddExpenses1;
    private javax.swing.JMenuItem frmIncome_miAddIncome1;
    private javax.swing.JMenuItem frmIncome_miCSV1;
    private javax.swing.JMenuItem frmIncome_miGoToReports1;
    private javax.swing.JMenuItem frmIncome_miPDF1;
    private javax.swing.JMenuItem frmIncome_miSeeBudgets1;
    private javax.swing.JMenuItem frmIncome_miSeeExpenses1;
    private javax.swing.JMenuItem frmIncome_miSeeIncome1;
    private javax.swing.JMenu frmIncome_mnuExit1;
    private javax.swing.JMenu frmIncome_mnuExport1;
    private javax.swing.JMenu frmIncome_mnuOperations1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
