/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author larisasabalin
 */
public class Details extends javax.swing.JDialog {

    /**
     * Creates new form SeeBudget
     */
    public Details(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStatus6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jMenuBar7 = new javax.swing.JMenuBar();
        mnuOperations6 = new javax.swing.JMenu();
        frmSeeBudget_miAddIncome6 = new javax.swing.JMenuItem();
        frmSeeBudget_miAddExpenses6 = new javax.swing.JMenuItem();
        frmSeeBudget_miGoToReports6 = new javax.swing.JMenuItem();
        frmSeeBudget_miSeeBudgets6 = new javax.swing.JMenuItem();
        frmSeeBudget_miSeeExpenses6 = new javax.swing.JMenuItem();
        frmSeeBudget_miSeeIncome6 = new javax.swing.JMenuItem();
        mnuExport6 = new javax.swing.JMenu();
        frmSeeBudget_miCSV6 = new javax.swing.JMenuItem();
        frmSeeBudget_miPDF6 = new javax.swing.JMenuItem();
        frmSeeBudget_mnuExit6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblStatus6.setText("Status");
        getContentPane().add(lblStatus6, java.awt.BorderLayout.PAGE_END);

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable1);

        jLabel31.setText("Month");

        jLabel32.setText("Year");

        jLabel33.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jLabel33.setText("Budget by category");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);

        mnuOperations6.setText("Operations");

        frmSeeBudget_miAddIncome6.setText("Add Income");
        frmSeeBudget_miAddIncome6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmSeeBudget_miAddIncome6ActionPerformed(evt);
            }
        });
        mnuOperations6.add(frmSeeBudget_miAddIncome6);

        frmSeeBudget_miAddExpenses6.setText("Add Expenses");
        mnuOperations6.add(frmSeeBudget_miAddExpenses6);

        frmSeeBudget_miGoToReports6.setText("Go To Reports");
        mnuOperations6.add(frmSeeBudget_miGoToReports6);

        frmSeeBudget_miSeeBudgets6.setText("See Budget");
        frmSeeBudget_miSeeBudgets6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmSeeBudget_miSeeBudgets6ActionPerformed(evt);
            }
        });
        mnuOperations6.add(frmSeeBudget_miSeeBudgets6);

        frmSeeBudget_miSeeExpenses6.setText("See Expenses");
        mnuOperations6.add(frmSeeBudget_miSeeExpenses6);

        frmSeeBudget_miSeeIncome6.setText("See Income");
        mnuOperations6.add(frmSeeBudget_miSeeIncome6);

        jMenuBar7.add(mnuOperations6);

        mnuExport6.setText("Export");

        frmSeeBudget_miCSV6.setText("to CSV");
        mnuExport6.add(frmSeeBudget_miCSV6);

        frmSeeBudget_miPDF6.setText("to PDF");
        mnuExport6.add(frmSeeBudget_miPDF6);

        jMenuBar7.add(mnuExport6);

        frmSeeBudget_mnuExit6.setText("Exit");
        jMenuBar7.add(frmSeeBudget_mnuExit6);

        setJMenuBar(jMenuBar7);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void frmSeeBudget_miSeeBudgets6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmSeeBudget_miSeeBudgets6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frmSeeBudget_miSeeBudgets6ActionPerformed

    private void frmSeeBudget_miAddIncome6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmSeeBudget_miAddIncome6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frmSeeBudget_miAddIncome6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Details dialog = new Details(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem frmSeeBudget_miAddExpenses6;
    private javax.swing.JMenuItem frmSeeBudget_miAddIncome6;
    private javax.swing.JMenuItem frmSeeBudget_miCSV6;
    private javax.swing.JMenuItem frmSeeBudget_miGoToReports6;
    private javax.swing.JMenuItem frmSeeBudget_miPDF6;
    private javax.swing.JMenuItem frmSeeBudget_miSeeBudgets6;
    private javax.swing.JMenuItem frmSeeBudget_miSeeExpenses6;
    private javax.swing.JMenuItem frmSeeBudget_miSeeIncome6;
    private javax.swing.JMenu frmSeeBudget_mnuExit6;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JMenuBar jMenuBar7;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblStatus6;
    private javax.swing.JMenu mnuExport6;
    private javax.swing.JMenu mnuOperations6;
    // End of variables declaration//GEN-END:variables
}
