/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author larisasabalin
 */
public class SeeExpenses extends javax.swing.JDialog {

    /**
     * Creates new form SeeExpenses
     */
    public SeeExpenses(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStatus7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jMenuBar8 = new javax.swing.JMenuBar();
        mnuOperations7 = new javax.swing.JMenu();
        miAddIncome7 = new javax.swing.JMenuItem();
        miAddExpenses7 = new javax.swing.JMenuItem();
        miGoToReports7 = new javax.swing.JMenuItem();
        miSeeBudgets7 = new javax.swing.JMenuItem();
        miSeeExpenses7 = new javax.swing.JMenuItem();
        miSeeIncome7 = new javax.swing.JMenuItem();
        mnuExport7 = new javax.swing.JMenu();
        miCSV7 = new javax.swing.JMenuItem();
        miPDF7 = new javax.swing.JMenuItem();
        mnuExit7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblStatus7.setText("Status");
        getContentPane().add(lblStatus7, java.awt.BorderLayout.PAGE_END);

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable2);

        jLabel34.setText("Month");

        jLabel35.setText("Year");

        jLabel36.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jLabel36.setText("Expences by category");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel8, java.awt.BorderLayout.CENTER);

        mnuOperations7.setText("Operations");

        miAddIncome7.setText("Add Income");
        mnuOperations7.add(miAddIncome7);

        miAddExpenses7.setText("Add Expenses");
        mnuOperations7.add(miAddExpenses7);

        miGoToReports7.setText("Go To Reports");
        mnuOperations7.add(miGoToReports7);

        miSeeBudgets7.setText("See Budget");
        miSeeBudgets7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSeeBudgets7ActionPerformed(evt);
            }
        });
        mnuOperations7.add(miSeeBudgets7);

        miSeeExpenses7.setText("See Expenses");
        mnuOperations7.add(miSeeExpenses7);

        miSeeIncome7.setText("See Income");
        mnuOperations7.add(miSeeIncome7);

        jMenuBar8.add(mnuOperations7);

        mnuExport7.setText("Export");

        miCSV7.setText("to CSV");
        mnuExport7.add(miCSV7);

        miPDF7.setText("to PDF");
        mnuExport7.add(miPDF7);

        jMenuBar8.add(mnuExport7);

        mnuExit7.setText("Exit");
        jMenuBar8.add(mnuExit7);

        setJMenuBar(jMenuBar8);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miSeeBudgets7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSeeBudgets7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miSeeBudgets7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeeExpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeeExpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeeExpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeeExpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeeExpenses dialog = new SeeExpenses(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JMenuBar jMenuBar8;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblStatus7;
    private javax.swing.JMenuItem miAddExpenses7;
    private javax.swing.JMenuItem miAddIncome7;
    private javax.swing.JMenuItem miCSV7;
    private javax.swing.JMenuItem miGoToReports7;
    private javax.swing.JMenuItem miPDF7;
    private javax.swing.JMenuItem miSeeBudgets7;
    private javax.swing.JMenuItem miSeeExpenses7;
    private javax.swing.JMenuItem miSeeIncome7;
    private javax.swing.JMenu mnuExit7;
    private javax.swing.JMenu mnuExport7;
    private javax.swing.JMenu mnuOperations7;
    // End of variables declaration//GEN-END:variables
}
