/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author larisasabalin
 */
public class SeeIncome extends javax.swing.JDialog {

    /**
     * Creates new form SeeIncome
     */
    public SeeIncome(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStatus8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jComboBox10 = new javax.swing.JComboBox<>();
        jComboBox11 = new javax.swing.JComboBox<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jMenuBar9 = new javax.swing.JMenuBar();
        mnuOperations8 = new javax.swing.JMenu();
        miAddIncome8 = new javax.swing.JMenuItem();
        miAddExpenses8 = new javax.swing.JMenuItem();
        miGoToReports8 = new javax.swing.JMenuItem();
        miSeeBudgets8 = new javax.swing.JMenuItem();
        miSeeExpenses8 = new javax.swing.JMenuItem();
        miSeeIncome8 = new javax.swing.JMenuItem();
        mnuExport8 = new javax.swing.JMenu();
        miCSV8 = new javax.swing.JMenuItem();
        miPDF8 = new javax.swing.JMenuItem();
        mnuExit8 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblStatus8.setText("Status");
        getContentPane().add(lblStatus8, java.awt.BorderLayout.PAGE_END);

        jPanel10.setBackground(new java.awt.Color(204, 204, 255));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(jTable5);

        jLabel42.setText("Month");

        jLabel43.setText("Year");

        jLabel44.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jLabel44.setText("Income");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43)
                    .addComponent(jLabel44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel10, java.awt.BorderLayout.CENTER);

        mnuOperations8.setText("Operations");

        miAddIncome8.setText("Add Income");
        mnuOperations8.add(miAddIncome8);

        miAddExpenses8.setText("Add Expenses");
        mnuOperations8.add(miAddExpenses8);

        miGoToReports8.setText("Go To Reports");
        mnuOperations8.add(miGoToReports8);

        miSeeBudgets8.setText("See Budget");
        miSeeBudgets8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSeeBudgets8ActionPerformed(evt);
            }
        });
        mnuOperations8.add(miSeeBudgets8);

        miSeeExpenses8.setText("See Expenses");
        mnuOperations8.add(miSeeExpenses8);

        miSeeIncome8.setText("See Income");
        mnuOperations8.add(miSeeIncome8);

        jMenuBar9.add(mnuOperations8);

        mnuExport8.setText("Export");

        miCSV8.setText("to CSV");
        mnuExport8.add(miCSV8);

        miPDF8.setText("to PDF");
        mnuExport8.add(miPDF8);

        jMenuBar9.add(mnuExport8);

        mnuExit8.setText("Exit");
        jMenuBar9.add(mnuExit8);

        setJMenuBar(jMenuBar9);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miSeeBudgets8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSeeBudgets8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miSeeBudgets8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeeIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeeIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeeIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeeIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeeIncome dialog = new SeeIncome(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JMenuBar jMenuBar9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable5;
    private javax.swing.JLabel lblStatus8;
    private javax.swing.JMenuItem miAddExpenses8;
    private javax.swing.JMenuItem miAddIncome8;
    private javax.swing.JMenuItem miCSV8;
    private javax.swing.JMenuItem miGoToReports8;
    private javax.swing.JMenuItem miPDF8;
    private javax.swing.JMenuItem miSeeBudgets8;
    private javax.swing.JMenuItem miSeeExpenses8;
    private javax.swing.JMenuItem miSeeIncome8;
    private javax.swing.JMenu mnuExit8;
    private javax.swing.JMenu mnuExport8;
    private javax.swing.JMenu mnuOperations8;
    // End of variables declaration//GEN-END:variables
}
