package BIE;


import HelperClasses.*;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.math.BigDecimal;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.InputMismatchException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author larisasabalin
 */
public class Login extends javax.swing.JFrame {

    HelperClasses.Database db;
    User user;
    public static final String DATE_FORMAT_SQL = "yyyy/MM/dd";

    /**
     * Creates new form Login
     */
    public Login() {

        db = new HelperClasses.Database();
        initComponents();
    }

    private void close() {
        WindowEvent winClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSED);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
    }

 

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgInitialInfo = new javax.swing.JDialog();
        jPanel13 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        lbInitialInfoBudget = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        sldInitialInfoBudgetHome = new javax.swing.JSlider();
        lbInitialInfoBudgetHouse = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        sldInitialInfoBudgetFood = new javax.swing.JSlider();
        lbInitialInfoBudgetFood = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        sldInitialInfoBudgetChemicals = new javax.swing.JSlider();
        lbInitialInfoBudgetChemicals = new javax.swing.JLabel();
        sldInitialInfoBudgetCar = new javax.swing.JSlider();
        lbInitialInfoBudgetCar = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        sldInitialInfoBudgetOther = new javax.swing.JSlider();
        lbInitialInfoBudgetOther = new javax.swing.JLabel();
        InitialInfo_btnSave = new javax.swing.JButton();
        InitialInfo_btnCancel = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        tfInitialInfoIncome = new javax.swing.JTextField();
        tfInitialInfoExpenses = new javax.swing.JTextField();
        dlgRegistration = new javax.swing.JDialog();
        Registration = new javax.swing.JPanel();
        reg_btnRegister = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        reg_btnCancel = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        reg_tfName = new javax.swing.JTextField();
        reg_pfPassword = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        reg_pfRePassword = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        reg_tfFamilyName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        reg_tfDob = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        reg_tfFamilyCode = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnNewMb = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        tfName = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        btnCancel = new javax.swing.JButton();

        jPanel13.setBackground(new java.awt.Color(204, 204, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Initial budgeting", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans Typewriter", 0, 18))); // NOI18N

        jLabel56.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 13)); // NOI18N
        jLabel56.setText("Total budget:");

        lbInitialInfoBudget.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 13)); // NOI18N
        lbInitialInfoBudget.setText("...");

        jLabel63.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 13)); // NOI18N
        jLabel63.setText("House(Rent/Morgage):");

        lbInitialInfoBudgetHouse.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 13)); // NOI18N
        lbInitialInfoBudgetHouse.setText("...");

        jLabel65.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 13)); // NOI18N
        jLabel65.setText("Food:");

        lbInitialInfoBudgetFood.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 13)); // NOI18N
        lbInitialInfoBudgetFood.setText("...");

        jLabel67.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 13)); // NOI18N
        jLabel67.setText("Household chemical and personal products:");

        lbInitialInfoBudgetChemicals.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 13)); // NOI18N
        lbInitialInfoBudgetChemicals.setText("...");

        lbInitialInfoBudgetCar.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 13)); // NOI18N
        lbInitialInfoBudgetCar.setText("...");

        jLabel70.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 13)); // NOI18N
        jLabel70.setText("Car:");

        jLabel71.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 13)); // NOI18N
        jLabel71.setText("Other:");

        lbInitialInfoBudgetOther.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 13)); // NOI18N
        lbInitialInfoBudgetOther.setText("...");

        InitialInfo_btnSave.setText("Save");
        InitialInfo_btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InitialInfo_btnSaveActionPerformed(evt);
            }
        });

        InitialInfo_btnCancel.setText("Cancel");
        InitialInfo_btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InitialInfo_btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel63)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel13Layout.createSequentialGroup()
                            .addGap(291, 291, 291)
                            .addComponent(jLabel56)
                            .addGap(92, 92, 92)
                            .addComponent(lbInitialInfoBudget))
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(sldInitialInfoBudgetHome, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbInitialInfoBudgetHouse))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(sldInitialInfoBudgetFood, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(lbInitialInfoBudgetFood))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(sldInitialInfoBudgetChemicals, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(lbInitialInfoBudgetChemicals))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(sldInitialInfoBudgetCar, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(lbInitialInfoBudgetCar))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(sldInitialInfoBudgetOther, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(lbInitialInfoBudgetOther))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel65, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel67, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel70, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel71, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InitialInfo_btnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InitialInfo_btnSave)
                .addGap(31, 31, 31))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(lbInitialInfoBudget))
                .addGap(18, 18, 18)
                .addComponent(jLabel63)
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sldInitialInfoBudgetHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbInitialInfoBudgetHouse))
                .addGap(18, 18, 18)
                .addComponent(jLabel65)
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sldInitialInfoBudgetFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbInitialInfoBudgetFood))
                .addGap(18, 18, 18)
                .addComponent(jLabel67)
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sldInitialInfoBudgetChemicals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbInitialInfoBudgetChemicals))
                .addGap(18, 18, 18)
                .addComponent(jLabel70)
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sldInitialInfoBudgetCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbInitialInfoBudgetCar))
                .addGap(18, 18, 18)
                .addComponent(jLabel71)
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sldInitialInfoBudgetOther, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbInitialInfoBudgetOther))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InitialInfo_btnSave)
                    .addComponent(InitialInfo_btnCancel))
                .addGap(16, 16, 16))
        );

        dlgInitialInfo.getContentPane().add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel9.setBackground(new java.awt.Color(204, 204, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Entering initial financial information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans Typewriter", 0, 18))); // NOI18N

        jLabel46.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 13)); // NOI18N
        jLabel46.setText("Income for the last month:");

        jLabel47.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 13)); // NOI18N
        jLabel47.setText("Expenses for the last month:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46)
                    .addComponent(jLabel47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfInitialInfoIncome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfInitialInfoExpenses, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(tfInitialInfoIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfInitialInfoExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47))
                .addGap(21, 21, 21))
        );

        dlgInitialInfo.getContentPane().add(jPanel9, java.awt.BorderLayout.PAGE_START);

        dlgRegistration.setLocation(new java.awt.Point(450, 200));

        Registration.setBackground(new java.awt.Color(204, 204, 255));
        Registration.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registration:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans Typewriter", 1, 18))); // NOI18N

        reg_btnRegister.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 13)); // NOI18N
        reg_btnRegister.setText("Register");
        reg_btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_btnRegisterActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jLabel9.setText("Login name:");

        reg_btnCancel.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 13)); // NOI18N
        reg_btnCancel.setText("Cancel");
        reg_btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_btnCancelActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jLabel10.setText("Password:");

        reg_pfPassword.setText("jPasswordField1");

        jLabel13.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jLabel13.setText("Password verification:");

        reg_pfRePassword.setText("jPasswordField1");

        jLabel14.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jLabel14.setText("Family name:");

        jLabel1.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jLabel1.setText("DOB(YYYY/MM/DD)");

        reg_tfDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_tfDobActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jLabel15.setText("Unified Family Code:");

        javax.swing.GroupLayout RegistrationLayout = new javax.swing.GroupLayout(Registration);
        Registration.setLayout(RegistrationLayout);
        RegistrationLayout.setHorizontalGroup(
            RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrationLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(reg_btnCancel)
                        .addGap(27, 27, 27)
                        .addComponent(reg_btnRegister))
                    .addGroup(RegistrationLayout.createSequentialGroup()
                        .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(109, 109, 109)
                        .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reg_tfFamilyCode)
                            .addComponent(reg_tfFamilyName)
                            .addComponent(reg_pfPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(reg_tfName)
                            .addComponent(reg_tfDob)
                            .addComponent(reg_pfRePassword))))
                .addContainerGap())
        );
        RegistrationLayout.setVerticalGroup(
            RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(reg_tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(reg_pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reg_pfRePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reg_tfDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reg_tfFamilyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(reg_tfFamilyCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reg_btnRegister)
                    .addComponent(reg_btnCancel))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dlgRegistrationLayout = new javax.swing.GroupLayout(dlgRegistration.getContentPane());
        dlgRegistration.getContentPane().setLayout(dlgRegistrationLayout);
        dlgRegistrationLayout.setHorizontalGroup(
            dlgRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgRegistrationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Registration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgRegistrationLayout.setVerticalGroup(
            dlgRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgRegistrationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Create new account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans Typewriter", 1, 18))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Or if you are connecting for the first time, ");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("please click on \"Enter New Member\" button bellow ⬇︎");

        btnNewMb.setText("Enter New Member");
        btnNewMb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewMbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btnNewMb)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(btnNewMb)
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_END);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans Typewriter", 1, 18))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jLabel2.setText("Login name:");

        jLabel3.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jLabel3.setText("Password:");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        pfPassword.setText("jPasswordField1");
        pfPassword.setToolTipText("");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogin))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pfPassword)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnCancel))
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        String password = pfPassword.getText();
        String username = tfName.getText();
        
        String result = db.loginVerif(password, username);
        if (result.equals("success")) {
            try {
                HouseholdBIE welcome = new HouseholdBIE();
                welcome.pack();
                welcome.setVisible(true);
                this.setVisible(false);
            } catch (SQLException| NullPointerException ex) {
                JOptionPane.showMessageDialog(null,
                    "Error connecting to database: " + ex.getMessage(),
                    "Database error",
                    JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnNewMbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewMbActionPerformed
        dlgRegistration.pack();
        dlgRegistration.setVisible(true);
        //dlgInitialInfo.getContentPane().setBackground(Color.getHSBColor(154, 254, 25));
        this.setVisible(false);
    }//GEN-LAST:event_btnNewMbActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void InitialInfo_btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InitialInfo_btnSaveActionPerformed
        try {
            DecimalFormat formatter = new DecimalFormat("###.##");
            formatter.setParseBigDecimal(true);
            BigDecimal budget = (BigDecimal) formatter.parse(lbInitialInfoBudget.getText());
            BigDecimal expenses = (BigDecimal) formatter.parse(tfInitialInfoExpenses.getText());
            BigDecimal income = (BigDecimal) formatter.parse(tfInitialInfoIncome.getText());
            
            String categoryExpense ="GeneralExpenses";
            String categoryIncome="Income";
            String categoryBudget="GeneralBudget";
            
           
           Transaction tExpense = new Transaction(0, user.getId(), expenses, nowSQL(), categoryExpense);
           tExpense.insert();
           Transaction tIncome =new Transaction(0, user.getId(), income, nowSQL(), categoryIncome);
           tIncome.insert();
           //convert the constructor to reading the category type id
           //BudgetsMonthly bBudget =new BudgetsMonthly(0, user.getId(), categoryBudget, budget, nowSQL());
            dlgInitialInfo.setVisible(false);
            dlgRegistration.setVisible(false);
            Login firstLogin = new Login();
            firstLogin.setVisible(true);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this,
                    "Re-enter the budgeted values" + ex.getMessage(),
                    "Decimal Format Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_InitialInfo_btnSaveActionPerformed

    private void reg_btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_btnRegisterActionPerformed
        String familyName = reg_tfFamilyName.getText();
        //    Family f = new Family(0, familyName);
        //    f.insert();

        String resultUser = "";
        String resultFamily = "";

        String name = reg_tfName.getText();
        String password = new String(reg_pfPassword.getPassword());
        String rePassword = new String(reg_pfRePassword.getPassword());
        String familyCode = reg_tfFamilyCode.getText();
        System.out.println(password.equals(rePassword));
        try {
            comparePassword(password, rePassword);
            Date dob = strToDate(reg_tfDob.getText());

            Family family = new Family(0, familyName, familyCode);
            //family.deleteName(); // to be removed when we fix the situation with Family access.
            resultFamily = family.insert();
            System.out.println(resultFamily+"good");
            // we need to check here if it was successfully written 
            //and then give out the message on the successeful registration
            //the thing is in bad sequence of events.. have to figureit out.
            //the fields have to be first inserted an then the object has to be created.. 
            //the logic id now totaly off..
            user = new User(0, name, password, dob, familyName);
            System.out.println("after");
            resultUser = user.insertUser();
            System.out.println(resultUser+"good");

            if (resultUser.equals("")) {
                JOptionPane.showMessageDialog(this, "Registered successfully.");
                dlgInitialInfo.pack();
                dlgInitialInfo.setVisible(true);
                dlgRegistration.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, resultUser);
            }
        } catch (InputMismatchException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this,
                    "Re-enter your passwords." + ex.getMessage(),
                    "Passwords not matched!!!",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_reg_btnRegisterActionPerformed

    private void reg_btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_btnCancelActionPerformed
        dlgRegistration.setVisible(false);
    }//GEN-LAST:event_reg_btnCancelActionPerformed

    private void reg_tfDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_tfDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_tfDobActionPerformed

    private void InitialInfo_btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InitialInfo_btnCancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_InitialInfo_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InitialInfo_btnCancel;
    private javax.swing.JButton InitialInfo_btnSave;
    private javax.swing.JPanel Registration;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnNewMb;
    private javax.swing.JDialog dlgInitialInfo;
    private javax.swing.JDialog dlgRegistration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbInitialInfoBudget;
    private javax.swing.JLabel lbInitialInfoBudgetCar;
    private javax.swing.JLabel lbInitialInfoBudgetChemicals;
    private javax.swing.JLabel lbInitialInfoBudgetFood;
    private javax.swing.JLabel lbInitialInfoBudgetHouse;
    private javax.swing.JLabel lbInitialInfoBudgetOther;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JButton reg_btnCancel;
    private javax.swing.JButton reg_btnRegister;
    private javax.swing.JPasswordField reg_pfPassword;
    private javax.swing.JPasswordField reg_pfRePassword;
    private javax.swing.JTextField reg_tfDob;
    private javax.swing.JTextField reg_tfFamilyCode;
    private javax.swing.JTextField reg_tfFamilyName;
    private javax.swing.JTextField reg_tfName;
    private javax.swing.JSlider sldInitialInfoBudgetCar;
    private javax.swing.JSlider sldInitialInfoBudgetChemicals;
    private javax.swing.JSlider sldInitialInfoBudgetFood;
    private javax.swing.JSlider sldInitialInfoBudgetHome;
    private javax.swing.JSlider sldInitialInfoBudgetOther;
    private javax.swing.JTextField tfInitialInfoExpenses;
    private javax.swing.JTextField tfInitialInfoIncome;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
