import HelperClasses.*;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.InputMismatchException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class RunApp extends javax.swing.JFrame {


  public RunApp() {
    initComponents();
  }
  
  public Date strToDate(String str) {
    SimpleDateFormat sdf = new SimpleDateFormat("DD/MM/YYYY");
    Date sqlDate = new Date(Calendar.getInstance().getTime().getTime());
    try {
      java.util.Date utilDate  = sdf.parse(str);
      sqlDate = new Date(utilDate.getTime());
    } catch (ParseException ex) {
      System.out.println(ex.getMessage());
    }
    return sqlDate;
  }
  
  public void comparePassword(String password, String rePassword) {
    if (password.equals(rePassword)) {
      JOptionPane.showMessageDialog(null, "Passwords matched!");
    } else {
      throw new InputMismatchException();
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    dlgRegistration = new javax.swing.JDialog();
    Registration = new javax.swing.JPanel();
    reg_btnRegister = new javax.swing.JButton();
    jLabel7 = new javax.swing.JLabel();
    reg_btnCancel = new javax.swing.JButton();
    jLabel8 = new javax.swing.JLabel();
    reg_tfName = new javax.swing.JTextField();
    reg_pfPassword = new javax.swing.JPasswordField();
    jLabel11 = new javax.swing.JLabel();
    reg_pfRePassword = new javax.swing.JPasswordField();
    jLabel12 = new javax.swing.JLabel();
    reg_tfFamilyName = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    reg_tfDob = new javax.swing.JTextField();
    Login = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    btnLogin = new javax.swing.JButton();
    tfName = new javax.swing.JTextField();
    pfPassword = new javax.swing.JPasswordField();
    btnCancel = new javax.swing.JButton();
    SignUp = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    btnNewMb = new javax.swing.JButton();

    dlgRegistration.setLocation(new java.awt.Point(450, 200));

    Registration.setBackground(new java.awt.Color(204, 204, 255));
    Registration.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registration:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans Typewriter", 1, 18))); // NOI18N

    reg_btnRegister.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 13)); // NOI18N
    reg_btnRegister.setText("Register");
    reg_btnRegister.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        reg_btnRegisterActionPerformed(evt);
      }
    });

    jLabel7.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
    jLabel7.setText("Login name:");

    reg_btnCancel.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 13)); // NOI18N
    reg_btnCancel.setText("Cancel");
    reg_btnCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        reg_btnCancelActionPerformed(evt);
      }
    });

    jLabel8.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
    jLabel8.setText("Password:");

    reg_pfPassword.setText("jPasswordField1");

    jLabel11.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
    jLabel11.setText("Password verification:");

    reg_pfRePassword.setText("jPasswordField1");

    jLabel12.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
    jLabel12.setText("Family name:");

    jLabel1.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
    jLabel1.setText("DOB");

    reg_tfDob.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        reg_tfDobActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout RegistrationLayout = new javax.swing.GroupLayout(Registration);
    Registration.setLayout(RegistrationLayout);
    RegistrationLayout.setHorizontalGroup(
      RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(RegistrationLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(RegistrationLayout.createSequentialGroup()
            .addComponent(jLabel11)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addGroup(RegistrationLayout.createSequentialGroup()
                .addComponent(reg_btnCancel)
                .addGap(27, 27, 27)
                .addComponent(reg_btnRegister))
              .addGroup(RegistrationLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(reg_tfDob)
                  .addComponent(reg_pfRePassword, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))))
          .addGroup(RegistrationLayout.createSequentialGroup()
            .addComponent(jLabel8)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(reg_pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(RegistrationLayout.createSequentialGroup()
            .addComponent(jLabel7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(reg_tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(RegistrationLayout.createSequentialGroup()
            .addComponent(jLabel1)
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(RegistrationLayout.createSequentialGroup()
            .addComponent(jLabel12)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(reg_tfFamilyName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    RegistrationLayout.setVerticalGroup(
      RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrationLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(RegistrationLayout.createSequentialGroup()
            .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(RegistrationLayout.createSequentialGroup()
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabel7)
                  .addComponent(reg_tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabel8)
                  .addComponent(reg_pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 45, Short.MAX_VALUE))
              .addGroup(RegistrationLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabel11)
                  .addComponent(reg_pfRePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(18, 18, 18)
            .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel1)
              .addComponent(reg_tfDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(reg_tfFamilyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(RegistrationLayout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jLabel12)))
        .addGap(19, 19, 19)
        .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(reg_btnRegister)
          .addComponent(reg_btnCancel))
        .addContainerGap())
    );

    javax.swing.GroupLayout dlgRegistrationLayout = new javax.swing.GroupLayout(dlgRegistration.getContentPane());
    dlgRegistration.getContentPane().setLayout(dlgRegistrationLayout);
    dlgRegistrationLayout.setHorizontalGroup(
      dlgRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(dlgRegistrationLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(Registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    dlgRegistrationLayout.setVerticalGroup(
      dlgRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(dlgRegistrationLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(Registration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    Login.setBackground(new java.awt.Color(204, 204, 255));
    Login.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans Typewriter", 1, 18))); // NOI18N

    jLabel2.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
    jLabel2.setText("Login name:");

    jLabel3.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
    jLabel3.setText("Password:");

    btnLogin.setText("Login");
    btnLogin.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLoginActionPerformed(evt);
      }
    });

    pfPassword.setText("jPasswordField1");
    pfPassword.setToolTipText("");

    btnCancel.setText("Cancel");
    btnCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCancelActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
    Login.setLayout(LoginLayout);
    LoginLayout.setHorizontalGroup(
      LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
        .addGap(0, 0, 0)
        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel2)
          .addComponent(jLabel3))
        .addGap(30, 30, 30)
        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(LoginLayout.createSequentialGroup()
            .addComponent(btnCancel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
            .addComponent(btnLogin))
          .addComponent(tfName)
          .addComponent(pfPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
        .addGap(31, 31, 31))
    );
    LoginLayout.setVerticalGroup(
      LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
        .addContainerGap(23, Short.MAX_VALUE)
        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(15, 15, 15)
        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnLogin)
          .addComponent(btnCancel))
        .addGap(28, 28, 28))
    );

    SignUp.setBackground(new java.awt.Color(204, 204, 255));
    SignUp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Create new account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans Typewriter", 1, 18))); // NOI18N

    jLabel4.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(0, 51, 51));
    jLabel4.setText("Or if you are connecting for the first time, ");

    jLabel5.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(0, 51, 51));
    jLabel5.setText("please click on \"Enter New Member\" button bellow ⬇︎");

    btnNewMb.setText("Enter New Member");
    btnNewMb.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnNewMbActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout SignUpLayout = new javax.swing.GroupLayout(SignUp);
    SignUp.setLayout(SignUpLayout);
    SignUpLayout.setHorizontalGroup(
      SignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(SignUpLayout.createSequentialGroup()
        .addGap(14, 14, 14)
        .addGroup(SignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel5)
          .addComponent(jLabel4)
          .addGroup(SignUpLayout.createSequentialGroup()
            .addGap(104, 104, 104)
            .addComponent(btnNewMb)))
        .addContainerGap(27, Short.MAX_VALUE))
    );
    SignUpLayout.setVerticalGroup(
      SignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignUpLayout.createSequentialGroup()
        .addContainerGap(44, Short.MAX_VALUE)
        .addComponent(jLabel4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel5)
        .addGap(18, 18, 18)
        .addComponent(btnNewMb)
        .addGap(28, 28, 28))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(SignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Login, SignUp});

    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(SignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(30, Short.MAX_VALUE))
    );

    layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Login, SignUp});

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    
  }//GEN-LAST:event_btnLoginActionPerformed

  private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    System.exit(0);
  }//GEN-LAST:event_btnCancelActionPerformed

  private void btnNewMbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewMbActionPerformed
    dlgRegistration.pack();
    dlgRegistration.setVisible(true);
  }//GEN-LAST:event_btnNewMbActionPerformed

  private void reg_btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_btnRegisterActionPerformed
    String familyName = reg_tfFamilyName.getText();
//    Family f = new Family(0, familyName);
//    f.insert();
    String name = reg_tfName.getText();
    String password = new String(reg_pfPassword.getPassword());
    String rePassword = new String(reg_pfRePassword.getPassword());
    System.out.println(password.equals(rePassword));
    try {
      comparePassword(password, rePassword);
      Date dob = strToDate(reg_tfDob.getText());
      User user = new User(0, name, password, dob, familyName);
      user.insertUser();
      
      JOptionPane.showMessageDialog(this, "Registered successfully.");
    } catch (InputMismatchException ex) {
      System.out.println(ex.getMessage());
      JOptionPane.showMessageDialog(this, 
              "Re-enter your passwords." + ex.getMessage(),
              "Passwords not matched!!!", 
              JOptionPane.ERROR_MESSAGE);
    }
    
    
  }//GEN-LAST:event_reg_btnRegisterActionPerformed

  private void reg_btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_btnCancelActionPerformed
    dlgRegistration.setVisible(false);
  }//GEN-LAST:event_reg_btnCancelActionPerformed

  private void reg_tfDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_tfDobActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_reg_tfDobActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(RunApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(RunApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(RunApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(RunApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new RunApp().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel Login;
  private javax.swing.JPanel Registration;
  private javax.swing.JPanel SignUp;
  private javax.swing.JButton btnCancel;
  private javax.swing.JButton btnLogin;
  private javax.swing.JButton btnNewMb;
  private javax.swing.JDialog dlgRegistration;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JPasswordField pfPassword;
  private javax.swing.JButton reg_btnCancel;
  private javax.swing.JButton reg_btnRegister;
  private javax.swing.JPasswordField reg_pfPassword;
  private javax.swing.JPasswordField reg_pfRePassword;
  private javax.swing.JTextField reg_tfDob;
  private javax.swing.JTextField reg_tfFamilyName;
  private javax.swing.JTextField reg_tfName;
  private javax.swing.JTextField tfName;
  // End of variables declaration//GEN-END:variables
}
